"""Add current_story to Game model

Revision ID: 7bc738429c3f
Revises: 2b622575ebcb
Create Date: 2025-06-09 14:05:05.516467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc738429c3f'
down_revision: Union[str, None] = '2b622575ebcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('current_story_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'story', ['current_story_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'current_story_id')
    # ### end Alembic commands ###
