"""Add Guess model

Revision ID: af8c0d11553d
Revises: 7bc738429c3f
Create Date: 2025-06-09 14:16:13.203856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8c0d11553d'
down_revision: Union[str, None] = '7bc738429c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('guesser_id', sa.Integer(), nullable=False),
    sa.Column('guessed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guessed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['guesser_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guess')
    # ### end Alembic commands ###
